#!/bin/sh

dname=cudatext_0.7.0.0-1_amd64

dd=~/tmp/$dname
sudo rm -rf $dd
 
mkdir $dd
mkdir $dd/DEBIAN
cp debfiles/control $dd/DEBIAN

mkdir $dd/usr
mkdir $dd/usr/bin
mkdir $dd/usr/share
mkdir $dd/usr/share/cudatext
mkdir $dd/usr/share/pixmaps
mkdir $dd/usr/share/applications

cp ../app/cudatext $dd/usr/bin
cp debfiles/cudatext.desktop $dd/usr/share/applications
cp debfiles/cudatext-256.png $dd/usr/share/pixmaps
cp -r ../app/data $dd/usr/share/cudatext
cp -r ../app/readme $dd/usr/share/cudatext
cp -r ../app/settings_default $dd/usr/share/cudatext

sudo chown -R root:root $dd
dpkg-deb --build $dd ~/Public/$dname.deb
