#!/bin/sh
cd ~/cuda/cuda/app

dname=cudatext-win-x32

rm ~/Public/*.zip
zip -r ~/Public/$dname.zip data readme settings_default *.manifest *.dll py*.zip dlls/* py/*.py py/cuda_addonman/*.inf py/cuda_addonman/*.py py/cuda_make_plugin/*.inf py/cuda_make_plugin/*.py py/cuda_insert_time/*.inf py/cuda_insert_time/*.py

cd ~/Public/win_exe
zip ~/Public/$dname.zip cudatext.exe
