#!/bin/sh
cd ~/cuda/cuda/app

dname=cudatext-win-x32

rm ~/Public/*.zip
zip -r ~/Public/$dname.zip data readme settings_default py

cd ~/Public/win_exe
zip ~/Public/$dname.zip cudatext.exe *.manifest *.dll *.zip  
